<?php
	/*
	* AIM: Prepare Query for Ajax Server Files
	* 
	* DESCRIPTION: To display data in grids, 
	* a jQuery datatable plugin is used, 
	* the source of data used in populating the grids / tables by this plugin is obtained from a php server side file,
	* this file contains some group of action buttons for each record,
	* those action buttons are generated by this file
	*
	* WRITTEN ON: 18-08-2013
	* BY: PATRICK O. OGBUITEPU
	*
	*/
	if( ! class_exists( "cAudit" ) ){
		require_once $fakepointer.$pagepointer."classes/cAudit.php";
	}
	
	if( ! isset( $has_serial ) ){
		$has_serial = 1;
	}
	if( ! isset( $real_table ) ){
		$real_table = $controller_table;
	}
	//CHECK USER PRIVILEGE
	$use_cache = 1;
	$classname = $real_table;
	$mongo_options = array();
	
	$allow_view = permission( $current_user_session_details , 'display_all_records'  , $classname , $database_connection , $database_name );
	
	if(!(isset($_SESSION['key'])))exit;
	
	if(!($allow_view))exit;
	
	if( ! ( isset( $allow_no_lang ) && $allow_no_lang ) && ! defined( strtoupper( $classname ) ) ){
		if( ! ( load_language_file( array( 
			'id' => $classname , 
			'pointer' => $pagepointer, 
			'language' => 'US',//SELECTED_COUNTRY_ISO_CODE
		) ) && defined( strtoupper( $classname ) ) ) ){
			//REPORT INVALID TABLE ERROR
			$err = new cError('000017');
			$err->action_to_perform = 'notify';
			
			$err->class_that_triggered_error = 'c'.ucwords($classname).'.php';
			$err->method_in_class_that_triggered_error = '_language_initialization';
			$err->additional_details_of_error = 'no language file';
			echo json_encode( $err->error() );
			exit;
		}
	}
    
    if( isset( $current_user_session_details['role'] ) && isset( $current_user_session_details['id'] ) ){
        switch( strtolower( $current_user_session_details['role'] ) ){
        case 'seller':
        case 'buyer':
        case 'admin_seller':
        break;
        default:
            //admin users
            $admin_user = 1;
        break;
        }
    }
        
	$returning_html_data = '';
	$hbc = '';
	$hsbc = '';	
		
	//GET ALL FIELDS IN TABLE
	include "ajax_server_table_fields.php";
	
	/* DB table to use */
	//$sTable = "categories";
	
	/* 
	 * Paging
	 */
	$sLimit = "";
	$offset = 0;
	$numrows = 0;
	if ( isset( $_GET['iDisplayStart'] ) && $_GET['iDisplayLength'] != '-1' )
	{
		$sLimit = "LIMIT ".intval(  $_GET['iDisplayStart'] ).", ".
			intval( $_GET['iDisplayLength'] );
			$mongo_options[ 'limit' ] = $_GET['iDisplayLength'];
		
		//$offset  = intval($_GET['iDisplayStart']);  // skip this many rows
		//$numrows = intval($_GET['iDisplayLength']);  // return 5 rows
	}
	
	
	/*
	 * Ordering
	 */
	
	$static_fields = array(
        0 => 'created_role',
        1 => 'created_by',
        2 => 'creation_date',
        3 => 'modified_by',
        4 => 'modification_date',
    );
	$sOrder = "";
	if ( isset( $_GET['iSortCol_0'] ) && isset ( $_GET['iSortingCols'] ) )
	{	
		//Enable for Mysql
		--$_GET['iSortCol_0']; //disabled last
		//--$_GET['iSortCol_0']; //disabled last
		//++$_GET['iSortCol_0'];
		$fl2 = array();
		foreach( $form_label as $fk1 => $fk2 ){
			switch( $fk2[ 'display_position' ] ){
			case 'do-not-display-in-table':
			break;
			default:
				$fl2[ $fk1 ] = $fk2;
			break;
			}
		}
						// print_r( $form_label );
						// print_r( $_GET );
		$sOrder = "ORDER BY  ";
		$serials = array_column( $fl2, 'serial_num' );
		$plugin = array_unique( array_column( $form_label, 'plugin' ) );
		$table_table = array_unique( array_column( $form_label, 'table' ) );
		for ( $i=0 ; $i<intval( $_GET['iSortingCols'] ) ; $i++ )
		{
			if ( isset (  $_GET[ 'bSortable_'.intval($_GET['iSortCol_'.$i]) ] ) && $_GET[ 'bSortable_'.intval($_GET['iSortCol_'.$i]) ] == "true" )
			{
                $scol = intval( $_GET['iSortCol_'.$i] );
                $scol = isset( $serials[ $scol-1 ] ) ? $serials[ $scol-1 ] : $scol;
						// print_r( $scol );

                if( empty( $plugin ) ){
	                if( strlen( $scol ) == 2 ){
	                    $scol = '0'.$scol;
	                }else if( strlen( $scol ) == 1 ){
	                    $scol = '00'.$scol;
	                }
                }
				//Get Field Info
                
                $id = 'none';
                $tb = isset( $table_table[0] ) ? $table_table[0] : $controller_table;
                if( isset( $form_label[ $tb.$scol ] ) ){
                    $id = $tb.$scol;
                }
                
                $size = ( count( $displayed_table_columns ) );
                
                if( intval($scol) > $size ){
                    if( isset( $static_fields[ $scol - $size ] ) ){
                        $id = $static_fields[ $scol - $size ];
                    }
                }
				//CHECK FOR DATA TYPE
                switch( $id ){
                case 'creator_role':
                case 'none':
                break;
                default:
                    $sOrder .= "(`".$controller_table."`.`".$id."`) ".( $_GET['sSortDir_'.$i] ) .", ";
                    $mongo_options[ 'sort' ][ $id ] = -1;
                break;
                }
				
			}
		}
		
		$sOrder = substr_replace( $sOrder, "", -2 );
		if ( $sOrder == "ORDER BY" )
		{
			$sOrder = "";
			
			if( isset( $controller_table_real ) ){
				switch( $controller_table_real ){
				case 'cash_calls_reporting_view':
					$use_cache = 0;
				case 'cash_calls':
				case 'budget_details':
				default:
					if ( isset( $setx['order_by'] ) && $setx['order_by'] && ($sOrder == "ORDER BY" || $sOrder == "") ){
						$sOrder = $setx['order_by'];
					}else{
						$sOrder = "ORDER BY `".$controller_table."`.`modification_date` desc";
						$mongo_options[ 'sort' ][ 'modification_date' ] = -1;
					}
				break;
				}
			}else{
				$sOrder = "ORDER BY `".$controller_table."`.`modification_date` desc";
				$mongo_options[ 'sort' ][ 'modification_date' ] = -1;
			}
			
		}else{
			$sOrder .= ", `".$controller_table."`.`modification_date` desc";
			$mongo_options[ 'sort' ][ 'modification_date' ] = -1;
		}
		
	}
	
	
	if ( $sOrder == "ORDER BY" || $sOrder == "" ){
		$sOrder = "ORDER BY `".$controller_table."`.`modification_date` desc";
		$mongo_options[ 'sort' ][ 'modification_date' ] = -1;
	}
    //echo $sOrder; exit;
	/* 
	 * Filtering
	 * NOTE this does not match the built-in DataTables filtering which does it
	 * word by word on any field. It's possible to do here, but concerned about efficiency
	 * on very large tables, and MySQL's regex functionality is very limited
	 */
	$sWhere = "WHERE `".$controller_table."`.`record_status`='1'";
	$mongo_filter = array();
	
	$sJoin = "";
	$sJoin_count = "";
	$sGroup_count = "";
	$sGroup = "";
	
	$additional_where_of_query = "";
	
	$setx = isset( $g_more_data["session"] )?$g_more_data["session"]:array();
	// print_r( $setx ); exit;
	//$setx = isset( $g_more_data["session"] )?$g_more_data["session"]:array();
	$multiple_query = array();
	if( isset( $setx[ 'filter' ][ 'mquery' ]['table'] ) && $setx[ 'filter' ][ 'mquery' ]['table'] ){
		$multiple_query = $setx[ 'filter' ][ 'mquery' ];   
    }
	if( isset( $setx[ 'filter' ][ 'order' ] ) && $setx[ 'filter' ][ 'order' ] ){
        $sOrder = $setx[ 'filter' ][ 'order' ];
    }
	
	if( isset( $setx[ 'filter' ][ 'join' ] ) && $setx[ 'filter' ][ 'join' ] ){
        $sJoin .= $setx[ 'filter' ][ 'join' ];
    }
	
	if( isset( $setx[ 'filter' ][ 'additional_where' ] ) && $setx[ 'filter' ][ 'additional_where' ] ){
        $additional_where_of_query = $setx[ 'filter' ][ 'additional_where' ];
    }else if( isset( $_SESSION[ $table ][ 'filter' ][ 'additional_where' ] ) && $_SESSION[ $table ][ 'filter' ][ 'additional_where' ] ){
        $additional_where_of_query .= $_SESSION[ $table ][ 'filter' ][ 'additional_where' ];
    }
	
	if( isset( $setx[ 'filter' ][ 'join_count' ] ) && $setx[ 'filter' ][ 'join_count' ] ){
        $sJoin_count .= $setx[ 'filter' ][ 'join_count' ];
    }
	
	if( isset( $setx[ 'filter' ][ 'group_count' ] ) && $setx[ 'filter' ][ 'group_count' ] ){
        $sGroup_count .= $setx[ 'filter' ][ 'group_count' ];
    }
	
	if( isset( $setx[ 'filter' ][ 'group' ] ) && $setx[ 'filter' ][ 'group' ] ){
        $sGroup .= $setx[ 'filter' ][ 'group' ];
    }
	
	$sSelect = " `".$controller_table."`.* ";
	if( isset( $setx[ 'filter' ][ 'select' ] ) && $setx[ 'filter' ][ 'select' ] ){
        $sSelect = $setx[ 'filter' ][ 'select' ];
    }
	if( isset( $setx[ 'filter' ][ 'e_select' ] ) && $setx[ 'filter' ][ 'e_select' ] ){
        $sSelect .= $setx[ 'filter' ][ 'e_select' ];
    }
	
	// print_r( $setx ); exit;
	$sFrom = $sSelect;
	
	if( isset( $setx[ 'filter' ][ 'from' ] ) && $setx[ 'filter' ][ 'from' ] ){
        $sFrom .= $setx[ 'filter' ][ 'from' ];
    }else{
		$sFrom .= "FROM `".$database_name."`.`".$controller_table."`".$sJoin;
	}
	
	$sCountSelect = " COUNT( `".$controller_table."`.`id` ) as 'count' ";
	if( isset( $setx[ 'filter' ][ 'select_count' ] ) && $setx[ 'filter' ][ 'select_count' ] ){
		$sCountSelect = $setx[ 'filter' ][ 'select_count' ];
	}

	$sCount_From2 = "FROM `".$database_name."`.`".$controller_table."`";
	if( isset( $setx[ 'filter' ][ 'from_count' ] ) && $setx[ 'filter' ][ 'from_count' ] ){
		$sCount_From2 = $setx[ 'filter' ][ 'from_count' ];
	}
	$sCount_From = $sCountSelect . $sCount_From2 .$sJoin_count;
	
	
	//Apply Class Method Filtering
	if(isset($setx['filter']['show_deleted_records']) && $setx['filter']['show_deleted_records'] ){
		$sWhere = "WHERE `".$controller_table."`.`record_status`='0'";
		$mongo_filter = array( "record_status" => 0 );
	}
	
	//Apply Class Method Filtering
	if(isset($setx['filter']['selected_record']) && $setx['filter']['selected_record']){
		$sWhere .= $setx['filter']['selected_record'];
	}
	
	//Apply Class Method Filtering
	if(isset($setx['filter']['show_my_records']) && $setx['filter']['show_my_records']){
		$sWhere .= " AND ( `".$controller_table."`.`created_by`='".$current_user_session_details['id']."' ) ";
		$mongo_filter[ "created_by" ] = $current_user_session_details['id'];
	}
	
    $more_where = "";
    
	switch($table){
	case 'users':
		//Apply Class Method Filtering
		$u = new cUsers();
		if(isset($setx['filter']['show_my_user_account']) && $setx['filter']['show_my_user_account']==1){
			$more_where .= " AND `".$controller_table."`.`ID`='".$current_user_session_details['id']."'";
		}
        $more_where .= " AND ( `".$controller_table."`.`". $u->table_fields[ 'role' ] ."` != '1300130013' OR `".$controller_table."`.`". $u->table_fields[ 'role' ] ."` IS NULL ) ";
        $mongo_filter[ $u->table_fields[ 'role' ] ] = array( '$ne' => '1300130013' );
	break;
	case 'access_roles':
		//Apply Class Method Filtering
		$more_where .= " AND `".$controller_table."`.`id` != '1300130013'";
		$mongo_filter[ 'id' ] = array( '$ne' => '1300130013' );
	break;
	case 'payout_requests':
	case 'coupons':
	case 'tasks':
	case 'notifications':
        if( isset( $current_user_session_details['role'] ) && isset( $current_user_session_details['id'] ) ){
            switch( strtolower( $current_user_session_details['role'] ) ){
            case 'seller':
            case 'buyer':
            case 'admin_seller':
                $more_where .= " AND `".$controller_table."`.`created_by` = '" . $current_user_session_details['id'] . "'";
                $mongo_filter[ 'created_by' ] = $current_user_session_details['id'];
                
                $skip_page_pointers_for_files = 'engine/';
            break;
            default:
                //admin users
            break;
            }
        }
	break;
	}
	
	$having = '';
    if( isset( $setx[ 'filter' ][ 'having' ] ) && $setx[ 'filter' ][ 'having' ] ){
        $having = $setx[ 'filter' ][ 'having' ];
    }
    if( isset( $setx[ 'filter' ][ 'where' ] ) && $setx[ 'filter' ][ 'where' ] ){
        $sWhere .= $setx[ 'filter' ][ 'where' ];
    }
    if( isset( $_SESSION[ $table ][ 'filter' ][ 'where' ] ) && $_SESSION[ $table ][ 'filter' ][ 'where' ] ){
        $sWhere .= $_SESSION[ $table ][ 'filter' ][ 'where' ];
    }
	
			// print_r( $_SESSION[ $table ][ 'filter' ] );exit;
    $sWhere .= $more_where;
    
    
	if ( isset($_GET['sSearch']) && $_GET['sSearch'] != "" ){
		$ssfind = 0;
		$sWhere .= " AND (";
		
		for ( $i=0 ; $i<count($aColumns) ; $i++ )
		{
			if( isset( $form_label[ $aColumns[$i] ] ) ){
				//Get Field Info
				$field = $form_label[ $aColumns[$i] ];
				
				//CHECK FOR DATA TYPE
				switch($field['form_field']){
				case "select":
				case "multi-select":
				case "date":
					//Transform incoming data to matching key of options array
					$transformed_search = transform_search_value(( $_GET['sSearch'] ), $field, $controller_table);
					if( $transformed_search ){
						$sWhere .= "`".$controller_table."`.`".$aColumns[$i]."` LIKE '%".$transformed_search."%' OR ";
						$mongo_filter[ $aColumns[$i] ] = array( '$regex' => '^'.$transformed_search, '$options' => 'i' );
					}
				break;
				case 'html':
				case 'multiple_json_data':
				case 'single_json_data':
				case 'url':
				case 'tel':
				case 'email':
				case 'textarea-unlimited-med':
				case 'textarea-unlimited':
				case 'calculated':
				case 'textarea':
				case 'text':
					$sWhere .= "`".$controller_table."`.`".$aColumns[$i]."` LIKE '%".addslashes( $_GET['sSearch'] )."%' OR ";
					$mongo_filter[ $aColumns[$i] ] = array( '$regex' => '^'.$_GET['sSearch'], '$options' => 'i' );
				break;
				}
				$ssfind = 1;
			}
		}
		
		if( $ssfind ){
			/* 
			if( isset( $real_table_fields["data"] ) && isset( $form_label[ $real_table_fields["data"] ] ) ){
				$sWhere .= "`".$controller_table."`.`". $real_table_fields["data"] ."` LIKE '%".( $_GET['sSearch'] )."%' OR ";
			}
			*/
			
			$sWhere .= "`".$controller_table."`.`id` = '".addslashes( $_GET['sSearch'] )."' OR ";
			$mongo_filter[ 'id' ] = array( '$regex' => '^'.$_GET['sSearch'], '$options' => 'i' );
			if( $has_serial && clean_numbers( $_GET['sSearch'] ) ){
				$sWhere .= "`".$controller_table."`.`serial_num` = '".clean_numbers( $_GET['sSearch'] )."' OR ";
				$mongo_filter[ 'serial_num' ] = array( '$regex' => '^'. clean_numbers( $_GET['sSearch'] ), '$options' => 'i');
			}
		}
		
		$sWhere = substr_replace( $sWhere, "", -3 );
		$sWhere .= ')';
	}
	
	/* Individual column filtering */
	for ( $i=0 ; $i<count($aColumns) ; $i++ )
	{
		if ( isset($_GET['bSearchable_'.$i]) && $_GET['bSearchable_'.$i] == "true" && $_GET['sSearch_'.$i] != '' )
		{
			if ( $sWhere == "" || empty($mongo_filter) )
			{
				$sWhere = "WHERE `".$controller_table."`.`record_status`='1' AND ";
				$mongo_filter = array( 'record_status' => 1 );
			}
			else
			{
				$sWhere .= " AND ";
			}
			
			//Get Field Info
			$field = get_form_field_type($aColumns[$i]);
			//CHECK FOR DATA TYPE
			switch($field['form_type']){
			case "9":
			case "4":
				//Transform incoming data to matching key of options array
				$transformed_search = transform_search_value( ($_GET['sSearch_'.$i]), $field, $controller_table);
				if( $transformed_search ){
					$sWhere .= "`".$controller_table."`.`".$aColumns[$i]."` LIKE '%".$transformed_search."%' ";
					$mongo_filter[ $aColumns[$i] ] = array( '$regex' => '^'.$transformed_search, '$options' => 'i' );
				}
			break;
			default:
				$sWhere .= "`".$controller_table."`.`".$aColumns[$i]."` LIKE '%".($_GET['sSearch_'.$i])."%' ";
				$mongo_filter[ $aColumns[$i] ] = array( '$regex' => '^'.$_GET['sSearch_'.$i], '$options' => 'i' );
			break;
			}
			
		}
	}
	
	if ( isset($_GET['sSearchCustom']) && isset($_GET['sSearchValue']) && $_GET['sSearchValue'] != "" )
	{
		//@dan-31-mar-22
		$sxw = '';
		if( isset( $g_more_data["quick_details"][ $_GET['sSearchCustom'] ]["search_field"] ) && isset( $g_more_data["quick_details"][ $_GET['sSearchCustom'] ]["field"] ) && isset( $g_more_data["quick_details"][ $_GET['sSearchCustom'] ]["table"] ) ){
			
			$ctb = $g_more_data["quick_details"][ $_GET['sSearchCustom'] ]["table"];
			switch( $g_more_data["quick_details"][ $_GET['sSearchCustom'] ]["search_field"] ){
			case "serial_num":
				$sxw = doubleval( trim( $_GET['sSearchValue'] ) );
			break;
			default:
				$query = "SELECT `id` FROM `".$database_name."`.`".$ctb."` WHERE `record_status` = '1' AND `". $g_more_data["quick_details"][ $_GET['sSearchCustom'] ]["search_field"] ."` = '". addslashes( trim( $_GET['sSearchValue'] ) ) ."' ";
			
				$query_settings = array(
					'database'=>$database_name,
					'connect'=> $database_connection,
					'source_file'=>'ajax_server',
					'table' => $ctb,
					'tables' => array( $ctb ),
				);
				$query_settings[ 'query_type' ] = 'SELECT';
				$query_settings[ 'query' ] = $query;
				$query_settings[ 'set_memcache' ] = 1;

				$result = execute_sql_query( $query_settings );
				if( isset( $result[0]["id"] ) ){
					$sxw = $result[0]["id"];
				}
			break;
			}
			
			$sWhere .= " AND `".$controller_table."`.`".$g_more_data["quick_details"][ $_GET['sSearchCustom'] ]["field"]."` = '". $sxw ."' ";
		}
	}
	/*
	 * SQL queries
	 * Get data to display
	 */
	/**************************************************************************/
	$arr = array();
	$result = array();
	
	//CHECK IF ADVANCE SEARCH MODE IS ACTIVE
	//Set Temporary Search Query for Ajax_server
		
	$query_settings = array(
		'database'=>$database_name,
		'connect'=> $database_connection,
		'query_type'=>'SELECT',
		'source_file'=>'ajax_server',
		'offset'=>$offset,
		'number_of_rows'=>$numrows,
		'set_memcache'=>$use_cache,
		'tables'=>array( $controller_table ),

		//MongoDB
		'table' => $controller_table,
		'where' => $mongo_filter,
		'select' => $mongo_options,
		'hey' => 'ajax',
	);

	$sq = md5('search_query'.$_SESSION['key']);
	if(isset($_SESSION[$sq]) && is_array($_SESSION[$sq]) && isset($_SESSION[$sq][$controller_table]['where']) && isset($_SESSION[$sq][$controller_table]['from'])){
		$ss = $_SESSION[$sq][$controller_table];
		
		//$sFrom = " `".$controller_table."`.* FROM `".$database_name."`.`".$controller_table."` ";
		//$sCount_From = " COUNT( `".$controller_table."`.`id` ) as 'count' FROM `".$database_name."`.`".$controller_table."`";
		$sWhere = $ss['where'].$additional_where_of_query;
		
		if( isset( $ss[ 'join' ] ) && $ss[ 'join' ] ){
			$sFrom .= $ss[ 'join' ];
			$sCount_From .= $ss[ 'join' ];
		}
		
		if( isset( $ss[ 'group' ] ) && $ss[ 'group' ] ){
			$sGroup = $ss[ 'group' ];
		}
		
		$query = "SELECT ".$sFrom." ".$ss['where'].$additional_where_of_query.$having." ".$sGroup." ".$sOrder." ".$sLimit;
		
		$query_settings[ 'query_type' ] = $ss['select'];
		$query_settings[ 'query' ] = $query;
		$query_settings[ 'set_memcache' ] = 1;
		$query_settings[ 'tables' ] = array($controller_table);

		$result = execute_sql_query( $query_settings );
		//unset($_SESSION[$sq][$controller_table]);
	}else{
		$unions_count = array();
		$unions = array();
		if( isset( $multiple_query["tables"] ) && ! empty( $multiple_query["tables"] ) ){
			
			$query_settings[ 'tables' ] = array( $multiple_query["table"] );
			
			foreach( $multiple_query["tables"] as $sxk => $sxq ){
				if( isset( $sxq["select"] ) && $sxq["select"] && isset( $sxq["from"] ) && $sxq["from"] ){
					$sxx = $sxq["from"];
					
					if( isset( $sxq["join"] ) && $sxq["join"] ){
						$sxx .= $sxq["join"];
					}
					
					$sxx .= " WHERE `".$multiple_query["table"]."`.`record_status` = '1' ";
					
					if( isset( $sxq["where"] ) && $sxq["where"] ){
						$sxx .= $sxq["where"];
					}
					
					if( isset($_GET['sSearch']) && trim( $_GET['sSearch'] ) && isset( $sxq["search_fields"] ) && is_array( $sxq["search_fields"] ) && ! empty( $sxq["search_fields"] ) ){
						$s_search = array();
						
						foreach( $sxq["search_fields"] as $sff => $sfv ){
							$s_search[] = " `".$sxk."`.`". $sfv ."` LIKE '%". addslashes( trim( $_GET['sSearch'] ) ) ."%' ";
						}
						
						$sxx .= " AND ( ".implode(" OR ", $s_search )." ) ";
					}
					
					if( isset( $multiple_query["where"] ) && $multiple_query["where"] ){
						$sxx .= $multiple_query["where"];
					}
					
					$sxx_c = "SELECT COUNT(*) " . $sxx;
					$sxx = $sxq["select"] . $sxx;
					
					//by @2echo: removed this to enable sorting of edms
					if( ! defined("NWP_SORT_EDMS_FOLDERS_AND_FILES") ){
						$sxx .= " ORDER BY `".$sxk."`.`modification_date` desc ";
					}
					
					$unions_count[] = $sxx_c;
					$unions[] = $sxx;
					$query_settings[ 'tables' ][] = $sxk;
				}
			}
			
		}
		
		if( ! empty( $unions ) ){
			$query = "( " . implode( " ) UNION ( ", $unions ) ." ) ";
			//by @2echo: removed this to enable sorting of edms
			if( defined("NWP_SORT_EDMS_FOLDERS_AND_FILES") && NWP_SORT_EDMS_FOLDERS_AND_FILES ){
				$query .= " ORDER BY `modification_date` desc ";
			}
			$query .= $sLimit;
		}else{
			$query = "SELECT ".$sFrom." ".$sWhere.$additional_where_of_query.$having." ".$sGroup." ".$sOrder."  ".$sLimit;
		}
		$query_settings[ 'query' ] = $query;
		//$query_settings[ 'set_memcache' ] = 0;
		
		//echo $query;	exit;
		$result = execute_sql_query( $query_settings );
		
		//print_r($result);
	}
	
	//print_r($result);exit;
	if( isset( $result[0] ) && ! empty( $result[0] ) ){
		$arr = $result;
	}else{
		//REPORT INVALID TABLE ERROR
		$err = new cError('000001');
		$err->action_to_perform = 'notify';
		
		$err->class_that_triggered_error = 'ajax_server_query.php';
		$err->method_in_class_that_triggered_error = $controller_table;
		$err->additional_details_of_error = '';
		
		//echo json_encode( $err->error() );
		$err->error();
		//exit;
	}
    
?>