<?php
/**
 * report_config Class
 *
 * @used in  				report_config Function
 * @created  				Hyella Nathan | 14:57 | 30-Nov-2023
 * @database table name   	report_config
 */
	
	class cReport_config extends cCustomer_call_log{
		
		public $class_settings = array();
		
		private $current_record_id = '';
		
		public $customer_source = '';
		public $table_name = 'report_config';
		
		public $default_reference = '';
		
		public $label = 'Report Mails';
		
		private $associated_cache_keys = array(
			'report_config',
			'operators-tree-view' => 'operators-tree-view',
		);
		
		public $table_fields = array();
		
		protected $datatable_settings = array(
			'show_toolbar' => 1,				//Determines whether or not to show toolbar [Add New | Advance Search | Show Columns will be displayed]
				'show_add_new' => 1,			//Determines whether or not to show add new record button
				'show_advance_search' => 1,		//Determines whether or not to show advance search button
				'show_column_selector' => 1,	//Determines whether or not to show column selector button
				'show_edit_button' => 1,		//Determines whether or not to show edit button
				'show_delete_button' => 1,		//Determines whether or not to show delete button
				'show_refresh_cache' => 0,
				
				'utility_buttons' => array(
					'comments' => 1,
					//'tags' => 1,
					'view_details' => 1,
				),
				
			'show_timeline' => 0,				//Determines whether or not to show timeline will be shown
				//'timestamp_action' => $this->action_to_perform,	//Set Action of Timestamp
			
			'show_details' => 1,				//Determines whether or not to show details
			'show_serial_number' => 1,			//Determines whether or not to show serial number
			
			'show_verification_status' => 0,	//Determines whether or not to show verification status
			'show_creator' => 0,				//Determines whether or not to show record creator
			'show_modifier' => 0,				//Determines whether or not to show record modifier
			'show_action_buttons' => 0,			//Determines whether or not to show record action buttons
		);
			
		function __construct(){
			if( file_exists( dirname( __FILE__ ).'/dependencies/report_config.json' ) ){
				$return = json_decode( file_get_contents( dirname( __FILE__ ).'/dependencies/report_config.json' ), true );
				if( isset( $return[ "fields" ] ) )$this->table_fields = $return[ "fields" ];
				if( isset( $return[ "table_clone" ] ) )$this->table_clone = $return[ "table_clone" ];
			}
		}
	
		function report_config(){
			
			//INITIALIZE RETURN VALUE
			$returned_value = '';
			
			$this->class_settings['current_module'] = '';
			
			$this->class_settings[ 'project_task_data' ] = get_project_data();
			
			if(isset($_GET['module']))
				$this->class_settings['current_module'] = $_GET['module'];
			
			switch ( $this->class_settings['action_to_perform'] ){
			case 'create_new_record':
			case 'edit':
				$returned_value = $this->_generate_new_data_capture_form();
			break;
			case 'display_all_records':
				unset( $_SESSION[$this->table_name]['filter']['show_my_records'] );
				unset( $_SESSION[$this->table_name]['filter']['show_deleted_records'] );
				
				$returned_value = $this->_display_data_table();
			break;
			case 'display_deleted_records':
				$_SESSION[$this->table_name]['filter']['show_deleted_records'] = 1;
				
				$returned_value = $this->_display_data_table();
			break;
			case 'delete_from_popup2':
			case 'delete_from_popup':
			case 'delete':
				$returned_value = $this->_delete_records();
			break;
			case 'save':
				$returned_value = $this->_save_changes();
			break;
			case 'restore':
				$returned_value = $this->_restore_records();
			break;
			case 'display_all_records_frontend_history':
			case 'display_all_records_full_view_search':
			case 'display_all_records_full_view':
			case 'display_all_records_frontend':
				$returned_value = $this->_display_all_records_full_view2();
			break;
			case 'save_new_popup':
			case 'save_app_changes':
				$returned_value = $this->_save_app_changes2();
			break;
			case 'delete_app_manager':
			case 'delete_app_record':
				$returned_value = $this->_delete_app_record();
			break;
			case 'edit_popup_form_in_popup':
			case 'new_popup_form_in_popup':
			case 'new_popup_form':
			case 'edit_popup_form':
				$returned_value = $this->_new_popup_form2();
			break;
			case 'view_details2':
			case 'view_details':
				$returned_value = $this->_view_details2();
			break;
			case "search_form":
				$returned_value = $this->_search_form2();
			break;
			case 'refresh_cache':
				$returned_value = $this->_refresh_cache();
			break;
			case 'save_line_items':
				$returned_value = $this->_save_line_items();
			break;
			case 'report_auto_generation':
				$returned_value = $this->_report_auto_generation();
			break;
			case 'save_login_report':
			case 'display_autogenerated_report':
				$returned_value = $this->_autogenerated_report_handler();
			break;
			case 'm_and_e_status':
				$returned_value = $this->_m_and_e_status();
			break;
			}
			
			if( isset( $this->class_settings["callback"][ $this->table_name ][ $this->class_settings['action_to_perform'] ] ) && $this->class_settings["callback"][ $this->table_name ][ $this->class_settings['action_to_perform'] ] ){
				$callback = get_callback_functions( $this->class_settings["callback"][ $this->table_name ][ $this->class_settings['action_to_perform'] ] );
				if( is_array( $callback ) && ! empty( $callback ) )$returned_value = array_merge( $callback, $returned_value );
			}
			
			return $returned_value;
		}

		protected function _report_auto_generation(){

			function c_seconds( $a='' ){
				switch ( $a ) {
					case 'ss':
						return 1;
					case 'min':
						return 60;
					case 'hour':
						return 3600;
					case 'days':
						return 24 * 3600;
					case 'week':
						return 7 * 24 * 3600;
					case 'year':
						return 52 * 7 * 24 * 3600;
					default:
						return 0;
				}
			}
			
			$u = new cUsers();
			
			$u->class_settings = $this->class_settings;

			$a1 = new cAccess_roles();
			
			$a1->class_settings = $this->class_settings;

			$this->class_settings['overide_select'] = $this->_get_select() . ", `". $a1->table_name ."`.`". $a1->table_fields['data'] ."` AS 'role', CONCAT(`". $u->table_name ."`.`". $u->table_fields['firstname'] ."`, ' ', `". $u->table_name ."`.`". $u->table_fields['lastname'] ."`) AS 'name', `". $u->table_name ."`.`". $u->table_fields['email'] ."` AS 'email' ";

			$this->class_settings['join'] = "JOIN `". $this->class_settings['database_name'] ."`.`". $u->table_name ."` ON `". $this->table_name ."`.`". $this->table_fields['user'] ."` = `". $u->table_name ."`.`id` ";

			$this->class_settings['join'] .= " JOIN `". $this->class_settings['database_name'] ."`.`". $a1->table_name ."` ON `". $u->table_name ."`.`". $u->table_fields['role'] ."` = `". $a1->table_name ."`.`id`";

			$this->class_settings['where'] = " AND `". $a1->table_name ."`.`". $a1->table_fields['data'] ."` REGEXP '". $this->table_name .".l_notify.l_notify' ";
			
			$us = $this->_get_records();

			if( $us ){

				$d = date("U");
				
				$rid = [];

				$pr = get_project_data();

				$subject = $pr['project_title'] . " AUTO GENERATED REPORT";

				$vat = get_vat_mapping();
				
				foreach ( $us as $sval ) {

					$interval = $sval['interval_value'] * c_seconds( $sval['interval'] );
					
					if( ( $d - (int)$sval['last_notification'] ) > (int)$interval ){
						
						$rid[] = $sval['id'];
						
						$sval['role'] = isset( $sval['role'] ) && $sval['role'] ? json_decode( $sval['role'], true ) : [];
						
						$vat2 = get_report_source_types( $sval['role'] );

						$content = "<p>Kindly be notified of your auto generated reports.</p>";
						
						$content .= "<ol>";
						
						$bff = array_reduce( explode(':::', $sval['report']), function($a, $b) use( $vat, $vat2, $sval ){
							
							$c = '';
							
							if( isset($vat2[ $b ]) && $vat2[ $b ] ){
								
								$url = defined("HYELLA_FRONTEND_URL") && HYELLA_FRONTEND_URL ? HYELLA_FRONTEND_URL : '';

								$url .= '?a=1';
								
								$url .= '&rr='. rawurlencode( base64_encode( $sval['id'] ) );
								
								if( isset($vat[ $b ]) ){
									$url .= '&br='. rawurlencode( base64_encode( $vat[ $b ]) );
								}
								
								$c = '<li><a href="'. $url .'" target="_blank">' .( $vat2[ $b ] ) . " Report". '</a></li>'; 
							}

							return $a . $c;
						});

						$content .= ( $bff ? $bff : '<p class="text-warning"><b>Access Denied</b><br>You do not have access to any report</p>' );
						
						$content .= "</ol>";
						
						$not = array(
							"content" => $content,
							"subject" => $subject,
							"single_email" => $sval[ "email" ],
							"single_name" => $sval[ "name" ]
						);
						
						$this->_send_email_notification( $not, [] );

						usleep(2500);
					}
				}

				if( $rid ){
					$this->_update_records( array(
						'where' => " `id` IN ('". implode("', '", $rid) ."') ",
						'field_and_values' => array(
							$this->table_fields['last_notification'] => [ 'value' => date("U") ]
						)
					) );

					return ['executed' => 1];
				}
			}
			
			return ['executed' => 0];
		}
		
		protected function _view_details2(){
			
			$filename = '';
				
			$handle = "#dash-board-main-content-area";
			if( ( isset( $this->class_settings[ 'html_replacement_selector' ] ) && $this->class_settings[ 'html_replacement_selector' ] ) ){
				$handle = "#" . $this->class_settings[ 'html_replacement_selector' ];
				$this->class_settings[ 'data' ][ 'params' ] = '&html_replacement_selector=' . $this->class_settings[ 'html_replacement_selector' ];
				
				$this->class_settings[ 'data' ][ 'html_replacement_selector' ] = $this->class_settings[ 'html_replacement_selector' ];
			}
			
			$action_to_perform = $this->class_settings['action_to_perform'];
			$error_msg = '';
			$hide_buttons = isset( $_GET[ 'hide_buttons' ] ) ? $_GET[ 'hide_buttons' ] : '';
			$e_type = 'error';
			
			if( ! ( isset( $_POST["id"] ) && $_POST["id"] ) ){
				$error_msg = 'Invalid Reference';
			}
			
			switch( $action_to_perform ){
			case 'view_details2':
				if( ! $error_msg ){
					$this->class_settings["current_record_id"] = $_POST[ 'id' ];
					$e = $this->_get_record();
					if( isset( $e["id"] ) ){
						
					}else{
						$error_msg = 'Unable to retrieve patient details';
					}
				}
			break;
			}
			
			switch( $action_to_perform ){
			case 'control_panel':
				if( ! $error_msg ){
					$opt = array();
					if( isset( $_GET[ 'click_btn' ] ) && $_GET[ 'click_btn' ] )$opt[ 'click_btn' ] = $_GET[ 'click_btn' ];
					$id = $e['id'];
					$opt[ 'id' ] = $id;

					/* $opt[ 'general_tasks' ][ 'administer_vaccine_btn' ] = array(
						'action' => 'antenatal_care_progress',
						'todo' => 'show_capture_options&use_get_customer=1&customer='.$e[ 'customer' ],
						'title' => 'New Care Progress',
					); */

					$opt[ 'general_actions' ][ 'view_details' ] = array(
						'action' => $this->table_name,
						'todo' => 'view_details',
						'title' => 'View Details',
					);

					$opt[ 'details_todo' ] = 'view_details2';
					$opt[ 'title_text' ] = get_name_of_referenced_record( array( 'id' => $e[ 'customer' ], 'table' => 'customers' ) );
					$_GET[ 'hide_buttons' ] = 1;

					$this->class_settings[ 'open_module' ] = $opt;

					//set_current_customer( array( "customer" => $id ) );
					return $this->_open_module();
				}
			break;
			case 'view_details2':
				$_GET["modal"] = 1;
				$filename = "view-details.php";
					
				if( ! $error_msg ){
					if( isset( $e["id"] ) ){
						$this->_apply_basic_data_control( $e );
						
						$this->class_settings[ 'data' ][ 'selected_record' ] = $e["id"];
						$this->class_settings[ 'data' ][ 'table' ] = $this->table_name;
						
						
						$this->class_settings[ 'data' ][ 'utility_buttons' ] = $this->datatable_settings["utility_buttons"];
						$this->class_settings[ 'data' ][ 'more_actions' ] = $this->basic_data["more_actions"];
						$this->class_settings[ 'html' ] = array( 'html-files/templates-1/globals/custom-buttons.php' );
						
						$b["more_actions"] = $this->_get_html_view();
						$b["id"] = $e["id"];
						//$b["auth_data"] = $qd;
						
						$this->class_settings["data_items"] = array( $e["id"] => $e );
						$this->class_settings["other_params"] = $b;
					}else{
						$error_msg = 'Unable to Retrieve Record';
					}
				}
			break;
			}
			
			if( $error_msg ){
				return $this->_display_notification( array( "type" => $e_type, "message" => $error_msg ) );
			}
			
			if( $hide_buttons )$this->class_settings[ 'data' ][ 'hide_buttons' ] = $hide_buttons;
			
			$this->class_settings[ 'data' ][ 'no_columns' ] = isset( $_GET["no_column"] )?$_GET["no_column"]:'';
			if( isset( $this->plugin ) && $this->plugin ){
				$this->class_settings[ 'data' ][ 'plugin' ] = $this->plugin;
				if( $filename ){
					$this->class_settings["html_filename"] = array( $this->view_path . $filename );
				}
			}else{
				if( $filename ){
					$this->class_settings["html_filename"] = array( 'html-files/templates-1/package/'.HYELLA_PACKAGE.'/'.$this->table_name.'/'.$filename );
				}
			}
			
			$this->class_settings["modal_dialog_style"] = "width:40%;";
				
			$return = $this->_view_details();
			
			switch ( $this->class_settings['action_to_perform'] ){
			case 'view_details2':
				if( isset( $return["html_replacement_selector"] ) && $return["html_replacement_selector"] ){
					$return["html_replacement_selector"] = $handle;
				}
			break;
			}
			
			return $return;
		}
		
		protected function _search_form2(){
			$where = "";
			
			foreach( array( 'customer', 'staff_responsible' ) as $key ){
				if( isset( $this->table_fields[ $key ] ) && isset( $_POST[ $this->table_fields[ $key ] ] ) && $_POST[ $this->table_fields[ $key ] ] ){
					//$this->class_settings[ $key ] = $_POST[ $this->table_fields[ $key ] ];
					$where .= " AND `".$this->table_fields[ $key ]."` = '".$_POST[ $this->table_fields[ $key ] ]."' ";
				}
			}
			
			$key = 'date';
			if( isset( $_POST[ $this->table_fields[ $key ] ] ) && $_POST[ $this->table_fields[ $key ] ] ){
				$this->class_settings[ $key ] = convert_date_to_timestamp( $_POST[ $this->table_fields[ $key ] ] , 1 );
				$where .= " AND `".$this->table_fields[ $key ]."` >= " . $this->class_settings[ $key ];
			}
			
			$key = 'date';
			$skey = "_range";

			if( isset( $_POST[ $this->table_fields[ $key ] . $skey ] ) && $_POST[ $this->table_fields[ $key ] . $skey ] ){
				$this->class_settings[ $key ] = convert_date_to_timestamp( $_POST[ $this->table_fields[ $key ] . $skey ] , 2 );

				$where .= " AND `".$this->table_fields[ $key ]."` <= " . $this->class_settings[ $key ];
			}
			
			$this->class_settings[ "where" ] = $where;
			return $this->_search_form();
		}

		protected function _autogenerated_report_handler( $o = array() ){
			$error_msg = '';
			$e_type = 'error';
			$n_params = array();
			$js = array( 'set_function_click_event', 'prepare_new_record_form_new' );
		
			$handle = isset($this->class_settings['html_replacement_selector']) && $this->class_settings['html_replacement_selector'] ? $this->class_settings['html_replacement_selector'] : 'inventories-asset-center-sub';

			$bypass = isset($o['bypass']) && $o['bypass'] ? $o['bypass'] : 0;
		
			$action_to_perform = $this->class_settings['action_to_perform'];
		
			switch( $action_to_perform ){
				
				case 'display_autogenerated_report':

					$id = $rty = '';

					$e = isset($o['record']) && $o['record'] ? $o['record'] : [];

					if( isset($_GET['rr']) && $_GET['rr'] && (isset( $_GET['br']) && $_GET['br']) && !$bypass  ){
						
						$id = rawurldecode( base64_decode( trim( $_GET['rr']) ) );

						$rty = rawurldecode( base64_decode( trim( $_GET['br']  ) ) );

						$pattern = '/^[a-zA-Z0-9_\-]+$/';
						if ( !preg_match( $pattern, $id) ) {
						   $error_msg = "<h4><b>Invalid Report</b></h4><p>Report Settings Unavailable</p>";
						}
						
						if( !$error_msg ){
							if ( !preg_match($pattern, $rty ) ) {
							   $error_msg = "<h4><b>Invalid Report</b></h4><p>Report Settings Unavailable</p>";
							}							
						}
					}

					if( !$error_msg ){
						if( $bypass ){

							$id = isset($o['id']) && $o['id'] ? $o['id'] : $id;

							$rty = isset($o['rty']) && $o['rty'] ? $o['rty'] : $rty;
						}

						if( $bypass || $id ){

							if( !$e ){

								$this->class_settings['current_record_id'] = $id;
								
								$e = $this->_get_record();
							}

							if( isset($e['id']) && $e['id'] ){

								if( ($e['login'] == 'yes') && !$bypass ){
									
									$filename = 'login-form.php';

									$this->class_settings['data'] = array( 'id' => $id, 'rty' => $rty, 'html_replacement' => $handle );
									
									$this->class_settings['html'] = array( $this->view_path . $filename );
									
									$html = $this->_get_html_view();
									
									return array(
										'status' => 'new-status',
										'html_replacement' => $html,
										'html_replacement_selector' => '#'.$handle,
										'javascript_functions' => $js
									);
								}

								$vat2 = array_flip( get_vat_mapping() );

								if( isset( $vat2[ $rty ] ) && in_array( $vat2[ $rty ], explode(":::", $e['report']) ) ){

									if( $bypass ){

										if( $e['user'] != $this->class_settings['user_id'] ){

											$error_msg = "<h4><b>Access Denied</b></h4><p>You do not have access to this report</p>";
										}
									}

									if( !$error_msg ){

										$tb = "reports_bay";
										
										$in = $this->plugin_instance->load_class( array( 'class' => [ $tb ], 'initialize' => 1 ) );
										
										$_GET = array(
											'default' => 'default',
											'report' => $rty,
											'no_side_bar' => 1,
											'spd' => 1
										);

										$in[ $tb ]->class_settings['action_to_perform'] = 'display_dashboard';

										$return = $in[ $tb ]->$tb();

										if( $bypass ){
											$_SESSION = array();
											error_reporting (~E_ALL);
											session_destroy();
										}

										return $return;
									}

								}else{
									$error_msg = "<h4><b>Access Denied</b></h4><p>You do not have access to this report</p>";
								}

							}else{
								$error_msg = "<h4><b>Invalid Report</b></h4><p>Report Settings Unavailable</p>";
							}
						}else{
							$error_msg = "<h4><b>Invalid Report</b></h4><p>Missing Report Parameter</p>";
						}
					}

				break;
				case 'save_login_report':
					$form_params = isset($_POST['formParams']) && $_POST['formParams'] ? json_decode($_POST['formParams'], true) : [];
					if( ( isset( $_POST["email"] ) || isset( $_POST["username"] ) ) && isset( $_POST["password"] ) ){
						$email = trim( ( isset( $_POST["email"] ) && $_POST["email"] )?$_POST["email"]:'' );
						$email_key = 'email';
						if( ! $email ){
							$email = ( isset( $_POST["username"] ) && $_POST["username"] )?$_POST["username"]:'';
							$email_key = 'username';
						}
						
						$pass = $_POST["password"];
					}else{
						$error_msg = "Please provide valid email & password";
					}
					
					if( !$error_msg ){
						
						$authentication = new cAuthentication();
						
						$authentication->class_settings = $this->class_settings;
						
						$authentication->class_settings["table"] = 'users';
						
						$authentication->class_settings["username_key"] = $email_key;
						
						$authentication->class_settings["username"] = $email;
						
						$authentication->class_settings["password"] = md5( $pass . get_websalter() );
						
						$authentication->class_settings["upassword"] = $pass;

						$authentication->class_settings["action_to_perform"] = 'confirm_username_and_password';
						
						$returned_data  = $authentication->authentication();
						
						if( is_array($returned_data) && isset( $returned_data[ 'typ' ] ) && $returned_data[ 'typ' ] == 'authenticated' && isset($returned_data[ 'user_details' ][ 'user_id' ]) && $returned_data[ 'user_details' ][ 'user_id' ] ){
							
							$this->class_settings['user_id'] = $returned_data[ 'user_details' ][ 'user_id' ];
							$this->class_settings['action_to_perform'] = 'display_autogenerated_report';
							
							return $this->_autogenerated_report_handler( array( 
								'bypass' => 1, 
								'id' => isset($form_params['id']) && $form_params['id'] ? $form_params['id'] : '',
								'rty' => isset($form_params['rty']) && $form_params['rty'] ? $form_params['rty'] : '',
							) );

						}else{
							$error_msg = "User could not be authenticated. Please provide valid email & password";
							if( isset( $returned_data["msg"] ) && $returned_data["msg"] ){
								$error_msg = $returned_data["msg"];
							}
						}
					}
				break;
			}
		
			$error_msg = $error_msg ? $error_msg : '<h4><b>Unknown Error</b></h4><p>Please try again later</p>';
		
			$n_params['type'] = $e_type;

			$n_params['message'] = $error_msg;

			$n_params['manual_close'] = 1;

			if( $bypass ){
				$_SESSION = array();
				error_reporting (~E_ALL);
				session_destroy();
			}
		
			return $this->_display_notification( $n_params );
		}

		protected function _display_all_records_full_view2(){
			$where = '';
			$disable_btn = 0;
			$spilt_screen = 0;
			$action_to_perform = $this->class_settings[ 'action_to_perform' ];
			$show_form = 0;
			
			switch( $action_to_perform ){
			case "display_all_records_full_view_search":
			case "display_all_records_frontend_history":
				$show_form = 1;
				unset( $this->class_settings[ "full_table" ] );
			break;
			case "display_all_records_frontend":
				// $spilt_screen = 1;
				$this->class_settings['full_table'] = 1;
				$this->class_settings['show_popup_form'] = 1;
				$this->basic_data = [];
				$this->datatable_settings['utility_buttons'] = [];
			break;
			}
			
			if( $disable_btn ){
				$this->datatable_settings[ "show_add_new" ] = 0;
				$this->datatable_settings[ "show_edit_button" ] = 1;
				$this->datatable_settings[ "show_delete_button" ] = 0;
				unset( $this->basic_data['more_actions'] );
			}
			
			switch( $action_to_perform ){
			case "display_all_records_frontend_history":
				$this->datatable_settings[ "show_edit_button" ] = 1;
				unset( $this->basic_data['more_actions'] );
			break;
			}
			
			if( $show_form ){
				$this->class_settings[ "show_form" ] = 1;
				$this->class_settings[ "form_heading_title" ] = 'Search ' . $this->label; 
				$this->class_settings[ 'form_submit_button' ] = 'Search &rarr;';
				$this->class_settings[ 'form_action' ] = '?action='.$this->table_name.'&todo=search_form';
				$this->class_settings[ 'add_empty_select_option' ] = 1;
				
				foreach( $this->table_fields as $key => $val ){
					switch( $key ){
					case "date":
						$this->class_settings["form_values_important"][ $val ] = date("U");
						$this->class_settings["attributes"]["show_date_range"][ $val ] = 1;
						$this->class_settings["attributes"]["disable_required_field"][ $val ] = 1;
					break;
					case "staff_responsible":
					case "customer":
						$this->class_settings["attributes"]["disable_required_field"][ $val ] = 1;
					break;
					default:
						$this->class_settings["hidden_records"][$val] = 1;
					break;
					}
				}
			}

			if( $spilt_screen ){
				$this->class_settings[ "full_table" ] = 1;
				$this->class_settings[ "show_popup_form" ] = 1;
				$this->class_settings[ 'frontend' ] = 1;
				
				$this->datatable_settings["split_screen"] = array();
				
				$this->datatable_settings["datatable_split_screen"] = array(
					'action' => '?action='. $this->plugin .'&todo=execute&nwp_action=' . $this->table_name . '&nwp_todo=view_details2&no_column=1',
					'col' => 4,
					'content' => get_quick_view_default_message_settings(),
				);
			}
			
			return $this->_display_all_records_full_view();
		}

		protected function _save_app_changes2(){
			
			$ddx = array();
			$error = '';
			$e = array();
			$etype = 'error';
			$save_app = 1;
			
			$action_to_perform = $this->class_settings["action_to_perform"];
			
			switch( $action_to_perform ){
			case 'save_app_changes':
			break;
			}
			
			if( $error ){
				return $this->_display_notification( array( "type" => $etype, "message" => $error ) );
			}
			
			switch( $save_app ){
			case 1:
				$return = $this->_save_app_changes();
			break;
			case 2:
				$return = $this->_save_changes();
			break;
			case 3:
				$return = $this->_update_table_field();
			break;
			case 4:
				$return = $this->_save_line_items();
				if( $return )$return = array( 'saved_record_id' => 1 );
			break;
			}
			
			// print_r( $return );exit;
			if( isset( $return["saved_record_id"] ) && $return["saved_record_id"] ){
				
				$container = "#dash-board-main-content-area";
				if( ( isset( $this->class_settings[ 'html_replacement_selector' ] ) && $this->class_settings[ 'html_replacement_selector' ] ) ){
					$container = "#" . $this->class_settings[ 'html_replacement_selector' ];
				}
				
				switch( $action_to_perform ){
				case 'save_app_changes':
				break;
				}
				
			}
			
			// Send notification to assigned persons
			switch( $action_to_perform ){
			case 'save_new_popup':
			break;
			}
			
			return $return;
		}
		
		protected function _new_popup_form2(){
			$action_to_perform = $this->class_settings['action_to_perform'];
			$this->class_settings["skip_link"] = 1;

			$this->class_settings['hidden_records'][ $this->table_fields['last_notification'] ] = 1;
			
			switch ( $action_to_perform ){
			case 'edit_popup_form_in_popup':
			case 'edit_popup_form':
				$_POST["mod"] = 'edit-'.md5($this->table_name);
				$this->class_settings["modal_title"] = 'Edit ' . $this->label;
				$this->class_settings["override_defaults"] = 1;
				
				//$this->class_settings[ "hidden_records" ][ $this->table_fields["task_type"] ] = 1;
			break;
			default:
			break;
			}
			
			//$this->class_settings["modal_callback"] = 'nwCustomers.loadForm';
			
			$this->class_settings['form_submit_button'] = 'Save '.$this->label.' &rarr;';
			return $this->_new_popup_form();
		}

		protected function _m_and_e_status( $o = array() ){
			$error_msg = '';
			$e_type = 'error';
			$n_params = array();
			$js = array( 'set_function_click_event', 'prepare_new_record_form_new' );
		
			$handle = isset($this->class_settings['html_replacement_selector']) && $this->class_settings['html_replacement_selector'] ? $this->class_settings['html_replacement_selector'] : 'inventories-asset-center-sub';
		
			$action_to_perform = $this->class_settings['action_to_perform'];
		
			switch( $action_to_perform ){
				case 'm_and_e_status':
					$nwp = new cNwp_endpoint;
					$nwp->class_settings = $this->class_settings;
					$tb = 'endpoint';
					$tb1 = 'endpoint_log';
					$in = $nwp->load_class( array( 'class' => [ $tb, $tb1 ], 'initialize' => 1 ) );
					$in[ $tb ]->class_settings['overide_select'] = " `". $in[ $tb ]->table_name ."`.`id` AS 'id', MAX(`". $in[ $tb1 ]->table_name ."`.`". $in[ $tb1 ]->table_fields['date'] ."`) AS 'date', `". $in[ $tb ]->table_name ."`.`". $in[ $tb ]->table_fields['status'] ."` AS 'status' ";
					$in[ $tb ]->class_settings['join'] = "JOIN `". $in[ $tb ]->class_settings['database_name'] ."`.`". $in[ $tb1 ]->table_name ."` ON `". $in[ $tb ]->table_name ."`.`id` = `". $in[ $tb1 ]->table_name ."`.`". $in[ $tb1 ]->table_fields['endpoint'] ."`";
					$in[ $tb ]->class_settings['where']  = " AND ( `". $in[ $tb ]->table_name ."`.`". $in[ $tb ]->table_fields['recurrence_value'] ."` <> 0 AND `". $in[ $tb ]->table_name ."`.`". $in[ $tb ]->table_fields['recurrence_value'] ."` IS NOT NULL ) AND (`". $in[ $tb1 ]->table_name ."`.`". $in[ $tb1 ]->table_fields['parent'] ."` IS NULL  OR  `". $in[ $tb1 ]->table_name ."`.`". $in[ $tb1 ]->table_fields['parent'] ."` = '')";
					$in[ $tb ]->class_settings['group'] = " GROUP BY `". $in[ $tb ]->table_name ."`.`id` ";
					$data['endpoint'] = $in[ $tb ]->_get_records( array( 'index_field' => 'id' ) );


					$bdpk = "bg-endpoint_log-retention-in-progress";
					$bdpk2 = "bg-endpoint_log-audit-backup-retention-in-progress";

					$data['next_clear_endpoint_trail'] = 0;
					$dirname = $this->class_settings["calling_page"] . "tmp/filescache/bg-processes/". $tb1 . "/";
					if( file_exists( $dirname . '/'. $bdpk .'.json' ) ){
						$ltc = json_decode( file_get_contents( $dirname . '/'. $bdpk .'.json' ), true );
						if( isset( $ltc["next_check"] ) ){
							$data['next_clear_endpoint_trail'] = doubleval( $ltc["next_check"] );
						}
					}
					

					$data['next_clear_endpoint_sr_trail'] = 0;
					if( file_exists( $dirname . '/'. $bdpk2 .'.json' ) ){
						$ltc = json_decode( file_get_contents( $dirname . '/'. $bdpk2 .'.json' ), true );
						if( isset( $ltc["next_check"] ) ){
							$data['next_clear_endpoint_sr_trail'] = doubleval( $ltc["next_check"] );
						}
					}

					$data['next_clear_logger_trail'] = 0;
					$bdpk = "bg-log_main_logger-retention-in-progress";
					$dirname = $this->class_settings["calling_page"] . "tmp/filescache/bg-processes/log_main_logger/";
					if( file_exists( $dirname . '/'. $bdpk .'.json' ) ){
						$ltc = json_decode( file_get_contents( $dirname . '/'. $bdpk .'.json' ), true );
						if( isset( $ltc["next_check"] ) ){
							$data['next_clear_logger_trail'] = doubleval( $ltc["next_check"] );
						}
					}

					$this->class_settings['overide_select'] = " MAX(`". $this->table_fields['last_notification'] ."`) AS 'last_sent' ";
					$data['report_auto_generation'] = $this->_get_records();

					if ( defined('AUDIT_TRAIL_RETENTION_CYCLE') && AUDIT_TRAIL_RETENTION_CYCLE ) {
						$ckey = md5( 'audit_trail' );
						$settings = array(
							'cache_key' => $ckey,
							'directory_name' => 'audit_trail',
							'permanent' => 1
						);

						$fs = get_cache_for_special_values( $settings );
						$data['audit_retention_cache'] = isset( $fs['last_update'] ) && $fs['last_update'] ? $fs['last_update'] : 0;
					}
					$this->class_settings['data'] = $data;
					$filename = str_replace( "_", "-", $action_to_perform );
					$this->class_settings['html'] = array( $this->view_path . $filename );
					$html = $this->_get_html_view();
					return array(
						'status' => 'new-status',
						'html_replacement' => $html,
						'html_replacement_selector' => '#'. $handle,
						'javascript_functions' => $js
					);
				break;
			}
		
			$error_msg = $error_msg ? $error_msg : '<h4><b>Unknown Error</b></h4><p>Please try again later</p>';
			$n_params['type'] = $e_type;
			$n_params['message'] = $error_msg;
		
			return $this->_display_notification( $n_params );
		}
		
		protected function _apply_basic_data_control( $e = array() ){
			
			//check if method is defined in custom-buttons
			if( isset( $e["action_to_perform"] ) && $e["action_to_perform"] ){
				$pos = strpos( json_encode( $this->basic_data['more_actions'] ), $e["action_to_perform"] );
				if ($pos === false) {
					return;
				}
			}
						 
			if( isset( $e["action_to_perform"] ) && $e["action_to_perform"] ){
				$pos = strpos( json_encode( $this->basic_data['more_actions'] ), $e["action_to_perform"] );
				if ($pos === false) {
					return $this->_display_notification( array( "type" => "error", "message" => "<h4>Access Denied</h4>The status of the " . $this->label . " does not permit this action" ) );
				}
			}
		}
			
		public $basic_data = array(
			'access_to_crud' => 1,	//all crud functions (add, edit, view, delete) will be available in access control
			//'exclude_from_crud' => array(),
			'special_actions' => array(
				'l_notify' => array(
					'title' => 'Receive Report Emails',
					'todo' => 'l_notify',
					'type' => '',
				),
				'rt_opt' => array(
					'label' => 'Specific Report Category',
					'todo' => 'get_all_report_ac_types',
					'type' => 'function'
				),
			),
		);
	}
	
	function report_config(){
		if( file_exists( dirname( __FILE__ ).'/dependencies/report_config.json' ) ){
			$return = json_decode( file_get_contents( dirname( __FILE__ ).'/dependencies/report_config.json' ), true );
			if( isset( $return[ "labels" ] ) ){
				if( isset( $return[ "fields" ] ) ){

					$key = $return[ "fields" ][ "user" ];
					$return[ "labels" ][ $key ][ 'calculations' ] = array(
						'type' => 'record-details',
						'reference_table' => 'users',
						'reference_keys' => array( 'firstname', 'lastname' ),
						'form_field' => 'text',
						'variables' => array( array( $key ) ),
					);
					
					$return[ "labels" ][ $key ][ 'form_field' ] = 'calculated';
					$return[ "labels" ][ $key ][ 'class' ] = 'select2 allow-clear';
					$return[ "labels" ][ $key ][ 'attributes' ] = ' action="?action=users&todo=get_select2" minlength="2" ';

					$key = $return[ "fields" ][ "report" ];
					// $return[ "labels" ][ $key ][ 'attributes' ] = ' multiple ';
					$return[ "labels" ][ $key ][ 'class' ] = ' select2 ';

					$key = $return[ "fields" ][ "interval_value" ];
					$return[ "labels" ][ $key ][ 'attributes' ] = ' min="1" ';

				}
				return $return[ "labels" ];
			}
		}
	}
?>