 CREATE TABLE `meta_data2`.`non_frequent_changes__sr` ( `id` varchar(33) NOT NULL ,  `date` int(11) DEFAULT NULL ,  `device` varchar(100) DEFAULT NULL ,  `model` varchar(200) DEFAULT NULL ,  `status` varchar(100) DEFAULT NULL ,  `center` varchar(100) DEFAULT NULL ,  `custodian` varchar(100) DEFAULT NULL ,  `purpose` text DEFAULT NULL ,  `serial_number` varchar(200) DEFAULT NULL ,  `os_name` varchar(200) DEFAULT NULL ,  `storage` decimal(20,4) DEFAULT NULL ,  `ram` decimal(20,4) DEFAULT NULL ,  `imsi` varchar(200) DEFAULT NULL ,  `imei` varchar(200) DEFAULT NULL ,  `camera` varchar(200) DEFAULT NULL ,  `screen_size` decimal(20,4) DEFAULT NULL ,  `screen_resolution` varchar(200) DEFAULT NULL ,  `architecture` varchar(200) DEFAULT NULL ,  `otg` varchar(200) DEFAULT NULL ,  `printer` varchar(200) DEFAULT NULL ,  `country` varchar(100) DEFAULT NULL ,  `state` varchar(100) DEFAULT NULL ,  `lga` varchar(100) DEFAULT NULL ,  `data` mediumtext DEFAULT NULL , `serial_num` int(11) NOT NULL, `creator_role` varchar(100) DEFAULT NULL, `created_source` varchar(100) DEFAULT NULL, `created_by` varchar(100) DEFAULT NULL, `creation_date` int(11) DEFAULT NULL, `modified_source` varchar(100) DEFAULT NULL, `modified_by` varchar(100) DEFAULT NULL, `modification_date` int(11) DEFAULT NULL, `ip_address` varchar(100) DEFAULT NULL, `device_id` text NOT NULL, `record_status` varchar(2) DEFAULT NULL ) ENGINE=InnoDB DEFAULT CHARSET=latin1 ; 
ALTER TABLE `meta_data2`.`non_frequent_changes__sr` ADD PRIMARY KEY (`serial_num`), ADD UNIQUE KEY `id` (`id`) ; 
ALTER TABLE `meta_data2`.`non_frequent_changes__sr` MODIFY `serial_num` int(11) NOT NULL AUTO_INCREMENT ; 
ALTER TABLE `meta_data2`.`non_frequent_changes` ADD INDEX(`device`) ; 
ALTER TABLE `meta_data2`.`non_frequent_changes__sr` ADD INDEX(`device`) ; 
ALTER TABLE `meta_data2`.`non_frequent_changes` ADD INDEX(`status`) ; 
ALTER TABLE `meta_data2`.`non_frequent_changes__sr` ADD INDEX(`status`) ; 
ALTER TABLE `meta_data2`.`non_frequent_changes` ADD INDEX(`center`) ; 
ALTER TABLE `meta_data2`.`non_frequent_changes__sr` ADD INDEX(`center`) ; 
ALTER TABLE `meta_data2`.`non_frequent_changes` ADD INDEX(`custodian`) ; 
ALTER TABLE `meta_data2`.`non_frequent_changes__sr` ADD INDEX(`custodian`) ; 
ALTER TABLE `meta_data2`.`non_frequent_changes` ADD INDEX(`country`) ; 
ALTER TABLE `meta_data2`.`non_frequent_changes__sr` ADD INDEX(`country`) ; 
ALTER TABLE `meta_data2`.`non_frequent_changes` ADD INDEX(`state`) ; 
ALTER TABLE `meta_data2`.`non_frequent_changes__sr` ADD INDEX(`state`) ; 
ALTER TABLE `meta_data2`.`non_frequent_changes` ADD INDEX(`lga`) ; 
ALTER TABLE `meta_data2`.`non_frequent_changes__sr` ADD INDEX(`lga`) ; 
ALTER TABLE `meta_data2`.`non_frequent_changes` ADD INDEX(`record_status`) ; 
ALTER TABLE `meta_data2`.`non_frequent_changes__sr` ADD INDEX(`record_status`) ; 
